# Generated by Django 5.0.3 on 2024-04-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_address_category_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Books", "Books"),
                    ("Clothing", "Clothing"),
                    ("Home and Garden", "Home and Garden"),
                    ("Toys and Games", "Toys and Games"),
                    ("Beauty and Health", "Beauty and Health"),
                    ("Sports and Outdoors", "Sports and Outdoors"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
