# Generated by Django 5.0.3 on 2024-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="price",
            field=models.DecimalField(decimal_places=2, default=70.99, max_digits=10),
            preserve_default=False,
        ),
    ]
