# Generated by Django 5.0.3 on 2024-05-07 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_remove_order_listing_order_listings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="winning_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winning_bid_listing",
                to="auctions.bid",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bidder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids_listing",
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bids",
            field=models.ManyToManyField(
                related_name="listing_bids", to="auctions.bid"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="orders",
            field=models.ManyToManyField(
                related_name="listing_orders", to="auctions.order"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="listings",
            field=models.ManyToManyField(
                related_name="order_listings", to="auctions.listing"
            ),
        ),
    ]
