# Generated by Django 5.0.3 on 2024-05-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_listing_watchlist_alter_address_id_alter_bid_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlisted_by", to="auctions.watchlist"
            ),
        ),
    ]
